### ISSUE TITLE
Enhancing the Wallet Details Page

### ISSUE THREAD

**Issue by kshitizvardhan** [Open-Source-Chandigarh/Expense-Tracker#11]
# Enhancing the Wallet Details Page

## Description

The "Wallet Details Page" is a component or feature within your application.

## Objective

The objective of this task is to improve the user experience of the Wallet Details Page. The enhancements may include 
- Improving the user interface
- Adding Transitions and Animations

**Comment by kshitizvardhan** [comment]
@BamaCharanChhandogi  Please assign me this issue.

**Comment by BamaCharanChhandogi** [comment]
I believe the wallet details page is not necessary. I don't know why this page was added to the project. We want to solve issue #9. You can check this issue and raise a PR.
So I am closing this issue.
